# 服务器运行配置项
server:
  port: 9000
  jwtKey: HORL)JUZ&AFIW*(XGS

captcha:
  length: 4
  lang: zh
  w: 107
  h: 36

# mysql配置项
db:
  driver: mysql
  host: <my self>
  port: 3306
  user: goshop
  pass: DcDe6CMx6FjMFfLa
  dbname: goshop
  charset: utf8mb4
  loc: Asia/Shanghai