# 服务器运行配置项
server:
  port: 9000
  jwtKey: HORL)JUZ&AFIW*(XGS

# mysql配置项
db:
  driver: mysql
  host: <my self host>
  port: 3306
  user: <my self user>
  pass: <my self pass>
  dbname: <my self dbname>
  charset: utf8mb4
  loc: Asia/Shanghai