# 服务器运行配置项
server:
  port: 9000
  jwtKey: HORL)JUZ&AFIW*(XGS

captcha:
  length: 4
  lang: zh
  w: 107
  h: 36

# mysql配置项
db:
  driver: mysql
  host: <my self>
  port: 3306
  user: <my self>
  pass: <my self>
  dbname: <my self>
  charset: utf8mb4
  loc: Asia/Shanghai