# 服务器运行配置项
server:
  port: 9000

# mysql配置项
db:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  user: <use yourself>
  pass: <use yourself>
  dbname: <use yourself>
  charset: utf8mb4
  loc: Asia/Shanghai